server:
  port: 9091
  
spring:
  messages:
    use-code-as-default-message: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOSTNAME}:5432/recipedb
    username: recipe
    password: recipe
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
    open-in-view: false
#      update, none

logging:
  level:
    root: INFO  

recipe:
  populatedb: true
  
  